name: spellspark-deployment-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8 # same as the Azure ML environment
  - pip
  - pip:
      - azureml-defaults
      - azureml-ai-monitoring
      - torch
      - pandas