channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - azureml-defaults
      - azureml-ai-monitoring
      - torch
      - pandas
name: spellspark-deployment-env